{
 "title": "Test",
 "time": { "from": "now-2m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Latency at Client",
   "type": "heatmap",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(client_latency_bucket[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(client_response[$__rate_interval])",
     "legendFormat": "{{status}}"
    },
    {
     "expr": "sum(rate(client_response[$__rate_interval]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Service Latency",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 13 },
   "targets": [
    { "expr": "2", "legendFormat": "maximum latency" },
    { "expr": "underload_average_latency", "legendFormat": "estimated latency" }
   ]
  },
  {
   "title": "Capacity Statistics",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 13 },
   "targets": [
    { "expr": "underload_capacity", "legendFormat": "capacity of {{component}}" },
    { "expr": "underload_size", "legendFormat": "size of {{component}}" },
    { "expr": "sum(underload_capacity) / 2", "legendFormat": "max throughput" }
   ]
  }
 ]
}